### ISSUE TITLE
Regression: "Allow creating of items" in input mask is not working for FEE

### ISSUE THREAD

**Issue by UB3RL33T** [MetaModels/contao-frontend-editing#37] opened 2020-06-08 15:29 UTC
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [ ] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/contao-frontend-editing/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |    7.2      |                                  |
| Contao version:                     |     4.9     |                                  |
| MetaModels version:                 | 2.2.x-dev         |         core & FEE                         |
| Installation via composer:          | yes |                            |
| Installed MetaModels packages:      |          |                                  |
| DCG version:                        |     2.2.x-dev     |                                  |

## Issue description

The option "Allow to creation of items" in an input mask for metamodels does not seem to work for FEE anymore.
When downgrading to 2.1 it works. 

## Steps to reproduce

1. Wire up a Metamodel with Frontend editing and an input mask
2. Enable creation of items in input mask: : 
![image](https://user-images.githubusercontent.com/21123031/84046657-acfcbb00-a9aa-11ea-9dd9-1273d2a13a53.png)
3. Go to frontend where the Metamodel is being used.

## Describe the behaviour of the application

When enabling the creation of items in a metamodel the "Add item"-link is not displayed, reason being that 
`$this->editEnable` https://github.com/MetaModels/contao-frontend-editing/blob/master/src/Resources/contao/templates/ce_metamodel_list_edit.html5#L4 is null.
Same goes for `$this->addUrl` https://github.com/MetaModels/contao-frontend-editing/blob/master/src/Resources/contao/templates/ce_metamodel_list_edit.html5#L5

## Describe the expected behaviour of the application

When enabling the creation of items the `$this->editEnable` flag should be true and the `$this->addUrl` property should contain the create-url for the metamodel used in frontend

This works for Contao 4.9 and MM 2.1 and therefore seems like a regression?

**Comment by zonky2** [comment] 2020-06-08 15:49
@richardhj and/or @baumannsven can you check this?

**Comment by amenk** [comment] 2020-06-25 07:45
*bump* This is quite a blocker for us :( Are there any recent findings for this? can we support somehow? Or shall we downgrade to MM2.1 on Contao 4.9 even if it is not supported?

**Comment by zonky2** [comment] 2020-06-25 07:48
@amenk can we have access to a/your test case?

**Comment by amenk** [comment] 2020-06-25 07:55
@zonky2 we don't have a minimal example yet - but actually the steps in the issue should suffice. Would project shell access help?

**Comment by zonky2** [comment] 2020-06-25 08:42
@amenk Shell access and access to your FEE - or you wait to next week... I have own project with FEE

**Comment by amenk** [comment] 2020-06-25 10:09
@zonky2 Okay, lets wait to next week, otherwise we would probably have to work with an NDA to share the project (if that is okay for you)
Please give us a note if you cannot reproduce it.

**Comment by zonky2** [comment] 2020-06-30 15:55
Workaround - adapt template `templates/ce_metamodel_list_edit.html5`  with link to your FEE edit page and `?act=create`

```diff
<?php $this->extend('ce_metamodel_list'); ?>

<?php $this->block('content'); ?>
-<?php if ($this->editEnable): ?>
-<div class="addUrl"><a href="<?= $this->addUrl ?>"><?= $this->addNewLabel ?></a></div>
-<?php endif; ?>
+<div class="addUrl"><a href="{{link_url::154}}?act=create">Datensatz erstellen</a></div>
<?php $this->parent(); ?>
<?php $this->endblock(); ?>
```

**Comment by UB3RL33T** [comment] 2020-07-02 09:01
I suppose this'll work for now, when using multiple FEE metamodels you'd have to create a template for each one.

Is there an ETA for a fix or will this be fixed with the release of 2.2?

**Comment by zonky2** [comment] 2020-07-02 09:44
@richardhj what's your schedule for the fix?

**Comment by zonky2** [comment] 2020-07-02 14:17
fixed in MM 2.2

**Closed as completed by zonky2** 2020-07-02 14:17 UTC
Labels: bug

**Comment by amenk** [comment] 2020-07-02 15:45
Thank you!

@UB3RL33T Please test and confirm the fix

**Comment by UB3RL33T** [comment] 2020-07-06 12:27
I can confirm the issue is fixed, thank you :)

**Comment by zonky2** [comment] 2020-07-06 12:28
thx
